version: '3.9'

services:
    app-contact-api:
        container_name: app-contact-api
        image: node:lts-alpine3.15
        working_dir: /usr/src/app
        ports:
            - "8000:3000"
        tty: true
        volumes:
            - "./:/usr/src/app"
        networks:
            - app-contact-network

networks:
    app-contact-network:
        external:
            true
